# Generated by Django 5.0.6 on 2024-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("dni", models.CharField(max_length=8, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("apepat", models.CharField(max_length=100)),
                ("apemat", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=255)),
                ("telefono", models.CharField(max_length=15)),
                ("estado", models.BooleanField(default=True)),
            ],
        ),
    ]
